---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release-oci-test-chart-0-1-0
  namespace: flux-system
spec:
  chart:
    spec:
      chart: test-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: source-oci-helm-test-chart-0-1-0
      version: 0.1.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: test-chart
